/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simple.route.manager.gui;
import java.awt.Dimension;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.UIManager;

/**
 *
 * @author Carlos H. Montenegro
 */
public class mainWindow extends javax.swing.JFrame {

    /**
     * Creates new form mainWindow
     */
    public mainWindow() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);
    }

    public mainWindow(String title){
        initComponents();
        this.setTitle(title);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mItemCargaDatos = new javax.swing.JMenuItem();
        mItemClente = new javax.swing.JMenuItem();
        menuConfig = new javax.swing.JMenu();
        mItemConfig = new javax.swing.JMenuItem();
        mItemMap = new javax.swing.JMenu();
        mItemRealTime = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Nuevo");

        mItemCargaDatos.setText("Carga de Datos");
        mItemCargaDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemCargaDatosActionPerformed(evt);
            }
        });
        jMenu1.add(mItemCargaDatos);

        mItemClente.setText("Cliente");
        mItemClente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemClenteActionPerformed(evt);
            }
        });
        jMenu1.add(mItemClente);

        jMenuBar1.add(jMenu1);

        menuConfig.setText("Configuración");
        menuConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConfigActionPerformed(evt);
            }
        });

        mItemConfig.setText("Parámetros Generales");
        mItemConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemConfigActionPerformed(evt);
            }
        });
        menuConfig.add(mItemConfig);

        jMenuBar1.add(menuConfig);

        mItemMap.setText("Vista de Mapa");

        mItemRealTime.setText("En Tiempo Real");
        mItemRealTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemRealTimeActionPerformed(evt);
            }
        });
        mItemMap.add(mItemRealTime);

        jMenuBar1.add(mItemMap);

        jMenu4.setText("Reportes");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1187, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 824, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mItemCargaDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemCargaDatosActionPerformed
        // TODO add your handling code here:
        JInternalFrame batchLoad = new loadWindow("Nueva Carga de Datos");
        
        batchLoad.setLocation((this.getSize().width - batchLoad.getSize().width)/2,(this.getSize().height- batchLoad.getSize().height)/2);
        this.add(batchLoad);
        batchLoad.setVisible(true);
    }//GEN-LAST:event_mItemCargaDatosActionPerformed

    private void menuConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConfigActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_menuConfigActionPerformed

    private void mItemConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemConfigActionPerformed
        // TODO add your handling code here:
        JInternalFrame config = new configWindow("Configuración");
        
        config.setLocation((this.getSize().width - config.getSize().width)/2, (this.getSize().height - config.getSize().height)/2);
        this.add(config);
        config.setVisible(true);
    }//GEN-LAST:event_mItemConfigActionPerformed

    private void mItemClenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemClenteActionPerformed
        // TODO add your handling code here:
        JInternalFrame clientView = new clientWindow("Clientes");
        clientView.setLocation((this.getSize().width - clientView.getSize().width)/2, (this.getSize().height - clientView.getSize().height)/2);
        this.add(clientView);
        clientView.setVisible(true);
    }//GEN-LAST:event_mItemClenteActionPerformed

    private void mItemRealTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemRealTimeActionPerformed
        // TODO add your handling code here:
        JInternalFrame mapView = new realTimeMapWindow();
        mapView.setLocation((this.getSize().width - mapView.getSize().width)/2, (this.getSize().height - mapView.getSize().height)/2);
        this.add(mapView);
        mapView.setVisible(true);
    }//GEN-LAST:event_mItemRealTimeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            /*
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }*/
             UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mItemCargaDatos;
    private javax.swing.JMenuItem mItemClente;
    private javax.swing.JMenuItem mItemConfig;
    private javax.swing.JMenu mItemMap;
    private javax.swing.JMenuItem mItemRealTime;
    private javax.swing.JMenu menuConfig;
    // End of variables declaration//GEN-END:variables
}
